//delete!!
export default {
    products: [{
            _id: "1",
            title: "1984",
            category: "Politics",
            image: "images/book-1.jpg",
            price: 10,
            author: "George Orwell",
            rating: 4.5,
            numReviews: 10,
            countInStock: 7,
        },

        {
            _id: "2",
            title: "Crime and Punishment",
            category: "Fiction",
            image: "images/book-2.jpg",
            price: 15,
            author: "Fyodor Dostoevsky",
            rating: 4.6,
            numReviews: 11,
            countInStock: 17,
        },

        {
            _id: "3",
            title: "The Alchemist",
            category: "Science Fiction & Fantasy",
            image: "images/book-3.jpg",
            price: 13,
            author: "Paulo Coelho",
            rating: 4.3,
            numReviews: 20,
            countInStock: 11,
        },

        {
            _id: "4",
            title: "The Song of Ice and Fire",
            category: "Fiction",
            image: "images/book-4.jpg",
            price: 30,
            author: "Martin, George R R",
            rating: 4.9,
            numReviews: 100,
            countInStock: 19,
        },
        {
            _id: "5",
            title: "Sapiens",
            category: "History",
            image: "images/book-5.jpg",
            price: 13,
            author: "Yuval Noah Harari",
            rating: 4.6,
            numReviews: 21,
            countInStock: 7,
        },
        {
            _id: "6",
            title: "The Atomic Habits",
            category: "Self-Help",
            image: "images/book-6.jpg",
            price: 8,
            author: "James Clear",
            rating: 4.5,
            numReviews: 10,
            countInStock: 12,
        },
    ],
};